/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;
import com.mysql.jdbc.Driver;
import com.toedter.calendar.JDateChooser;
import java.awt.HeadlessException;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import koneksi.koneksi;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.text.ParseException;
import java.util.Date;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import java.text.SimpleDateFormat;
import static form.Jadwal.nampungtgl;
import static form.form_obat.getTanggalFromTable;
import static form.form_pasien.nampungtgl;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.io.FileUtils;
/**
 *
 * @author MUHAMMAD YUSRIL
 */
public class detail_transaksi extends javax.swing.JFrame {

    /**
     * Creates new form detail_transaksi
     */
    public detail_transaksi() {
        initComponents();
        this.setLocationRelativeTo(null);;
        datatableTransaksi();
        comboBoxObat();
        comboBoxTransaksi();
    }
    
    public void kosong() {
        cmbDetail.setSelectedItem("-- Select --");
        cmbObat.setSelectedItem("-- Select --");
        txtharga.setText("");
    }

    public static String nampungtgl;

    public void datatableTransaksi() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("ID Detail");
        tbl.addColumn("ID Transaksi");
        tbl.addColumn("Nama Obat");
        tbl.addColumn("Harga"); 
        tabel.setModel(tbl);
        try {
            Statement statement = (Statement) koneksi.GetConnection().createStatement();
            ResultSet res = statement.executeQuery("SELECT * FROM detail_transaksi INNER JOIN transaksi ON detail_transaksi.Id_transaksi=transaksi.Id_Transaksi INNER JOIN obat ON detail_transaksi.kode_obat=obat.Kode_Obat");
            while (res.next()) {
                tbl.addRow(new Object[]{
                    res.getString("detail_transaksi.id_detail"),
                    res.getString("transaksi.Id_Transaksi"),
                    res.getString("obat.Nama_Obat"),
                    res.getString("detail_transaksi.harga")
                });
                tabel.setModel(tbl);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "salah");
            System.out.println(e.getMessage());
        }
    }
    
    public void comboBoxTransaksi() {
        try {
            Statement statement = (Statement) koneksi.GetConnection().createStatement();
            ResultSet res = statement.executeQuery("SELECT * FROM transaksi");
            while (res.next()) {
                cmbDetail.addItem(res.getString("Id_Transaksi"));
            }
            res.last();
            int jumlahdata = res.getRow();
            res.first();
        } catch (Exception e) {
        }
    }
    
    public void comboBoxObat() {
        try {
            Statement statement = (Statement) koneksi.GetConnection().createStatement();
            ResultSet res = statement.executeQuery("SELECT * FROM obat");
            while (res.next()) {
                cmbObat.addItem(res.getString("Nama_Obat"));
            }
            res.last();
            int jumlahdata = res.getRow();
            res.first();
        } catch (Exception e) {
        }
    }

    public void tampilObat() {
        try {
            Statement statement = (Statement) koneksi.GetConnection().createStatement();
            ResultSet res = statement.executeQuery("SELECT * FROM obat WHERE Nama_Obat = '" + cmbObat.getSelectedItem() + "'");
            while (res.next()) {
                txtObat.setText(res.getString("Kode_Obat"));
                txtharga.setText(res.getString("harga"));
            }
            res.close();
            statement.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        cmbDetail = new javax.swing.JComboBox<>();
        txtharga = new javax.swing.JTextField();
        jLabel136 = new javax.swing.JLabel();
        jLabel151 = new javax.swing.JLabel();
        jLabel156 = new javax.swing.JLabel();
        jLabel141 = new javax.swing.JLabel();
        txtObat = new javax.swing.JLabel();
        btnsimpan4 = new javax.swing.JPanel();
        jLabel103 = new javax.swing.JLabel();
        btnrefresh = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        btnedit = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        btndelete = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        cmbObat = new javax.swing.JComboBox<>();
        jLabel152 = new javax.swing.JLabel();
        jLabel157 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        btnedit1 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        txtDetail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setMinimumSize(new java.awt.Dimension(570, 515));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(570, 515));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(15, 88, 5));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/close.png"))); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/minimize.png"))); // NOI18N

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/maximize.png"))); // NOI18N

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/logo.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PUSKESMAS");

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TERPADU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(6, 6, 6)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel6))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel22)
                                .addComponent(jLabel23)
                                .addComponent(jLabel21))
                            .addComponent(jLabel7)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel20)
                        .addComponent(jLabel1)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 90));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel56.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel56.setText("Detail Pembayaran");
        jPanel2.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        cmbDetail.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select --" }));
        cmbDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDetailActionPerformed(evt);
            }
        });
        jPanel2.add(cmbDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 320, 30));
        jPanel2.add(txtharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 320, 30));

        jLabel136.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel136.setText("Harga");
        jPanel2.add(jLabel136, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel151.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel151.setText("Kode Transaksi");
        jPanel2.add(jLabel151, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel156.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel156.setText(":");
        jPanel2.add(jLabel156, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        jLabel141.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel141.setText(":");
        jPanel2.add(jLabel141, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        txtObat.setForeground(new java.awt.Color(240, 240, 240));
        jPanel2.add(txtObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 60, 20));

        btnsimpan4.setBackground(new java.awt.Color(0, 204, 51));
        btnsimpan4.setForeground(new java.awt.Color(255, 255, 255));
        btnsimpan4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsimpan4btnsimpanMouseClicked(evt);
            }
        });

        jLabel103.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel103.setForeground(new java.awt.Color(255, 255, 255));
        jLabel103.setText("Simpan");

        javax.swing.GroupLayout btnsimpan4Layout = new javax.swing.GroupLayout(btnsimpan4);
        btnsimpan4.setLayout(btnsimpan4Layout);
        btnsimpan4Layout.setHorizontalGroup(
            btnsimpan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnsimpan4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel103)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        btnsimpan4Layout.setVerticalGroup(
            btnsimpan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnsimpan4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel103)
                .addContainerGap())
        );

        jPanel2.add(btnsimpan4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, 40));

        btnrefresh.setBackground(new java.awt.Color(204, 204, 0));
        btnrefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnrefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnrefreshMouseClicked(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Refresh");

        javax.swing.GroupLayout btnrefreshLayout = new javax.swing.GroupLayout(btnrefresh);
        btnrefresh.setLayout(btnrefreshLayout);
        btnrefreshLayout.setHorizontalGroup(
            btnrefreshLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnrefreshLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel38)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        btnrefreshLayout.setVerticalGroup(
            btnrefreshLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnrefreshLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel38)
                .addContainerGap())
        );

        jPanel2.add(btnrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, 40));

        btnedit.setBackground(new java.awt.Color(0, 0, 255));
        btnedit.setForeground(new java.awt.Color(255, 255, 255));
        btnedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btneditMouseClicked(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Edit");

        javax.swing.GroupLayout btneditLayout = new javax.swing.GroupLayout(btnedit);
        btnedit.setLayout(btneditLayout);
        btneditLayout.setHorizontalGroup(
            btneditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btneditLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel39)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        btneditLayout.setVerticalGroup(
            btneditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btneditLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel39)
                .addContainerGap())
        );

        jPanel2.add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, 40));

        btndelete.setBackground(new java.awt.Color(255, 0, 0));
        btndelete.setForeground(new java.awt.Color(255, 255, 255));
        btndelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndeleteMouseClicked(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Delete");

        javax.swing.GroupLayout btndeleteLayout = new javax.swing.GroupLayout(btndelete);
        btndelete.setLayout(btndeleteLayout);
        btndeleteLayout.setHorizontalGroup(
            btndeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btndeleteLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel41)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        btndeleteLayout.setVerticalGroup(
            btndeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btndeleteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel41)
                .addContainerGap())
        );

        jPanel2.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, 40));

        cmbObat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select --" }));
        cmbObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbObatActionPerformed(evt);
            }
        });
        jPanel2.add(cmbObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 320, 30));

        jLabel152.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel152.setText("Nama Obat");
        jPanel2.add(jLabel152, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel157.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel157.setText(":");
        jPanel2.add(jLabel157, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 490, 100));

        btnedit1.setBackground(new java.awt.Color(255, 102, 0));
        btnedit1.setForeground(new java.awt.Color(255, 255, 255));
        btnedit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnedit1MouseClicked(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("kembali");

        javax.swing.GroupLayout btnedit1Layout = new javax.swing.GroupLayout(btnedit1);
        btnedit1.setLayout(btnedit1Layout);
        btnedit1Layout.setHorizontalGroup(
            btnedit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnedit1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel42)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        btnedit1Layout.setVerticalGroup(
            btnedit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnedit1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel42)
                .addContainerGap())
        );

        jPanel2.add(btnedit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, 40));

        txtDetail.setForeground(new java.awt.Color(240, 240, 240));
        jPanel2.add(txtDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 60, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 560, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel21MouseClicked

    private void cmbDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDetailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDetailActionPerformed

    private void btnsimpan4btnsimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsimpan4btnsimpanMouseClicked
        // TODO add your handling code here:
        String detail = (String) cmbDetail.getSelectedItem();
        String obat = txtObat.getText();
        String harga = txtharga.getText();

        try {
            Statement statement = (Statement) koneksi.GetConnection().createStatement();
            statement.executeUpdate("insert into detail_transaksi VALUES (NULL,'" + detail + "','" + obat + "','" + harga + "')");
            statement.close();
            JOptionPane.showMessageDialog(null, "data berhasil disimpan");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "data gagal disimpan");
            System.out.println(e.getMessage());
        }
        datatableTransaksi();
        kosong();
    }//GEN-LAST:event_btnsimpan4btnsimpanMouseClicked

    private void btnrefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrefreshMouseClicked
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_btnrefreshMouseClicked

    private void btneditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditMouseClicked
        // TODO add your handling code here:
         String txtkd = txtDetail.getText();
        String detail = (String) cmbDetail.getSelectedItem();
        String obat = txtObat.getText();
        String harga = txtharga.getText();
;

        try {
            Statement statement = (Statement) koneksi.GetConnection().createStatement();
            statement.executeUpdate("UPDATE detail_transaksi SET id_transaksi ='" + detail + "', kode_obat ='" + obat + "', harga ='" + harga + "' WHERE id_detail ='" + txtkd + "'");
            statement.close();
            JOptionPane.showMessageDialog(null, "data berhasil diedit");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "data gagal diedit");
            System.out.println(e.getMessage());
        }
        datatableTransaksi();
        kosong();
    }//GEN-LAST:event_btneditMouseClicked

    private void btndeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeleteMouseClicked
        // TODO add your handling code here:
        String txtkd = txtDetail.getText();
        try {
            Statement statement = (Statement) koneksi.GetConnection().createStatement();
            statement.executeUpdate("delete from detail_transaksi where id_detail = '" + txtkd + "';");
            statement.close();
            JOptionPane.showMessageDialog(null, "data berhasil Dihapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "data gagal Dihapus");
        }
        datatableTransaksi();
        kosong();
    }//GEN-LAST:event_btndeleteMouseClicked

    private void cmbObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbObatActionPerformed
        // TODO add your handling code here:
        tampilObat();
    }//GEN-LAST:event_cmbObatActionPerformed

    private void btnedit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnedit1MouseClicked
        // TODO add your handling code here:
        new transaksi().show();
        this.dispose();
    }//GEN-LAST:event_btnedit1MouseClicked

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
         int i = tabel.getSelectedRow();

        String tgl;

        if (i >= 0) {
            txtDetail.setText((String) tabel.getValueAt(i, 0));
            cmbDetail.setSelectedItem((String) tabel.getValueAt(i, 1));
            cmbObat.setSelectedItem((String) tabel.getValueAt(i, 2));
            txtharga.setText((String) tabel.getValueAt(i, 3));
        }
    }//GEN-LAST:event_tabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(detail_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(detail_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(detail_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(detail_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new detail_transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btndelete;
    private javax.swing.JPanel btnedit;
    private javax.swing.JPanel btnedit1;
    private javax.swing.JPanel btnrefresh;
    private javax.swing.JPanel btnsimpan4;
    private javax.swing.JComboBox<String> cmbDetail;
    private javax.swing.JComboBox<String> cmbObat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel151;
    private javax.swing.JLabel jLabel152;
    private javax.swing.JLabel jLabel156;
    private javax.swing.JLabel jLabel157;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    private javax.swing.JLabel txtDetail;
    private javax.swing.JLabel txtObat;
    private javax.swing.JTextField txtharga;
    // End of variables declaration//GEN-END:variables
}
